/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsmkn8;

/**
 *
 * @author ASUS
 */
public class FormHelp extends javax.swing.JFrame {

    /**
     * Creates new form formhelp
     */
    public FormHelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsmkn8/Image/Banner Decrypt.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 628, 113);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cara Melakukan Enkripsi Adalah Sebagai Berikut :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 131, 339, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cara Melakukan Dekripsi Adalah Sebagai Berikut :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 261, 339, 17);

        jLabel2.setText("- Pertama pilih file yang akan di enkripsi dengan cara menekan tombol choose file.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 154, 530, 14);

        jLabel5.setText("- Pertama pilih file yang akan di dekripsi dengan cara menekan tombol choose file.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 289, 590, 14);

        jLabel6.setText("- masukkan password atau kunci enkripsi. password tersebut nantinya akan digunakan juga untuk");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 174, 560, 14);

        jLabel7.setText(" melakukan dekripsi,  jadi simpan password tersebut selama file masih dalam keadaan ter enkripsi.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 194, 550, 14);

        jLabel8.setText("- Setelah itu klik tombol enkripsi yang ada pada form, lalu pilih direktori penyimpanan file yang ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 214, 530, 14);

        jLabel9.setText("- Masukkan password atau kunci sesuai dengan password yang digunakan pada saat mengenkripsi file.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 309, 600, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Catatan :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 330, 64, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Pastikan password atau kunci yang digunakan disimpan dengan baik karna pada saat melakukan ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 354, 580, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("dekripsi, kunci tersebut tidak boleh berbeda sedikitpun.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 374, 314, 14);

        jLabel13.setText("sudah di enkripsi.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(31, 234, 380, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsmkn8/Image/Power-Button-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(589, 393, 38, 41);

        setSize(new java.awt.Dimension(628, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Login A = new Login();
        A.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHelp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
